apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-soeq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-soeq@sha256:a723f2c36fc02a44dd9d3336aa3a68da567324efb49627e8a0a4c06c66132bbc
        name: my-nodejs
        resources: {}
status: {}
